function [gas_map, binary_hotspots] = co2_jrge()

clc;
close all;

hdr_file = ...
'D:\downloads\co2-detection-hyperspectral-main\f250923t01p00r13_rfl.hdr';

bin_file = ...
'D:\downloads\co2-detection-hyperspectral-main\f250923t01p00r13_rfl.bin';

assert(isfile(hdr_file), ...
'HDR missing');

assert(isfile(bin_file), ...
'BIN missing');

%% =====================================
% READ HDR
%% =====================================

txt = fileread(hdr_file);

t = regexp( ...
txt,...
'samples\s*=\s*(\d+)',...
'tokens',...
'once');

samples = str2double(t{1});

t = regexp( ...
txt,...
'lines\s*=\s*(\d+)',...
'tokens',...
'once');

lines = str2double(t{1});

t = regexp( ...
txt,...
'bands\s*=\s*(\d+)',...
'tokens',...
'once');

bands = str2double(t{1});

fprintf( ...
'Metadata: %d x %d x %d\n',...
lines,...
samples,...
bands);

%% =====================================
% LOAD SMALL SUBSET
%% =====================================

cube = multibandread( ...
bin_file,...
[lines samples bands],...
'float32',...
0,...
'bsq',...
'ieee-le',...
{'Row','Range',[1 1000]},...
{'Column','Range',[1 1000]});

cube = double(cube);

%% =====================================
% WAVELENGTH
%% =====================================

w = regexp( ...
txt,...
'wavelength\s*=\s*\{([^}]*)\}',...
'tokens',...
'once');

wavelength = str2num(w{1});

wavelength = wavelength(:);

%% =====================================
% SCALE + CLEAN
%% =====================================

if max(cube(:))>10

cube = cube/10000;

end

cube(isnan(cube))=0;

cube(isinf(cube))=0;

cube(cube<0)=0;

%% =====================================
% DOWNSAMPLE
%% =====================================

cube = cube( ...
1:5:end,...
1:5:end,...
:);

[rows,cols,bands] = ...
size(cube);

reshapedData = ...
reshape( ...
cube,...
[],...
bands);

%% =====================================
% REFLECTANCE ESTIMATION
%% =====================================

reflectance_estimate = ...
reshapedData;

for i=1:size(reshapedData,1)

spec = ...
reshapedData(i,:);

if std(spec)<1e-10

continue;

end

reflectance_estimate(i,:) = ...
fnval( ...
csaps( ...
1:bands,...
spec,...
0.90),...
1:bands);

end

%% =====================================
% CO2 BAND
%% =====================================

absorp_band = ...
find( ...
wavelength>=2000 & ...
wavelength<=2100);

if isempty(absorp_band)

absorp_band = ...
round(bands/2);

end

%% =====================================
% JRGE
%% =====================================

gas_density = ...
median( ...
reflectance_estimate(:,absorp_band),...
2) ...
- ...
median( ...
reshapedData(:,absorp_band),...
2);

for iter=1:3

reflectance_estimate = ...
reflectance_estimate ...
+ ...
0.05 * ...
(reshapedData ...
- ...
reflectance_estimate);

gas_density = ...
median( ...
reflectance_estimate(:,absorp_band),...
2) ...
- ...
median( ...
reshapedData(:,absorp_band),...
2);

end

%% =====================================
% OUTPUT
%% =====================================

gas_map = ...
reshape( ...
gas_density,...
rows,...
cols);

gas_map = ...
gas_map ...
- ...
min(gas_map(:));

gas_map = ...
gas_map ./ ...
(max(gas_map(:))+eps);

thr = ...
graythresh(gas_map);

binary_hotspots = ...
gas_map > thr;

%% =====================================
% DISPLAY
%% =====================================

figure;

imagesc(gas_map);

axis image;

colorbar;

title('JRGE');

figure;

imshow(binary_hotspots);

title('Hotspots');

fprintf('Done\n');

end
